/* tslint:disable */
export default [
  "script-src 'self' *.leadpages.net *.gstatic.com *.google.com *.googleapis.com *.playwire.com *.facebook.com *.bootstrapcdn.com *.twitter.com *.spot.im",
  "script-src 'self' *.leadpages.net *.gstatic.com *.google.com *.googleapis.com *.playwire.com *.facebook.com *.bootstrapcdn.com",
  "script-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.gstatic.com *.google-analytics.com *.google.com *.solvemedia.com *.scorecardresearch.com *.googletagmanager.com *.googletagservices.com; child-s",
  "script-src 'self' *.gstatic.com *.google.com *.googleapis.com *.facebook.com *.bootstrapcdn.com *.twitter.com *.spot.im",
  "script-src 'self' 'unsafe-inline' 'unsafe-eval' data: ",
  "script-src 'self' * 'unsafe-inline'",
  "*.google.com *.gstatic.com *.google-analytics.com *.jwpcdn.com *.twimg.com *.twitter.com *.hydrax.net *.facebook.com *.googleapis.com *.facebook.net *.iomovies.info",
  "script-src 'self' 'unsafe-inline'",
  "script-src 'self' 'unsafe-eval' 'unsafe-inline' data: *.air.tv *.b2c.com *.chartbeat.com *.cheezburger.com *.chzbgr.com *.complex.com *.facebook.net *.google-analytics.com *.google.com *.gstatic.com *",
  "default-src http://*.pcmag.com https://*.pcmag.com 'unsafe-inline' 'unsafe-eval' data: blob: bootstrapcdn.com *.bootstrapcdn.com disqus.com *.disqus.com disquscdn.com *.disquscdn.com facebook.com *.fa",
  "cebook.com googleapis.com *.googleapis.com gstatic.com *.gstatic.com ign.com *.ign.com pinterest.com *.pinterest.com reddit.com *.reddit.com truste.com *.truste.com youtube.com *.youtube.com youtube-n",
  "script-src 'self' 'unsafe-eval' 'unsafe-inline' data: *.youtube.com *.ytimg.com *.google-analytics.com *.facebook.net *.complex.com *.b2c.com *.chartbeat.com *.chzbgr.com *.scorecardresearch.com *.air",
  "*.hypable.com *.stat-rock.com *.wibbitz.com *.googletagservices.com *.googleapis.com *.twitter.com *.google.com *.facebook.com *.google-analytics.com *.gstatic.com *.facebook.net *.alooma.com",
  "*.google.com *.gstatic.com *.widgetpack.com *.jwpcdn.com *.google-analytics.com *.povwideo.net *.clipwatching.com *.vshare.io *.rapidvideo.com *.fastplay.to *.facebook.com *.fbcdn.net",
  " data: *.fbcdn.net *.facebook.com *.google-analytics.com *.facebook.net *.bwwstatic.com *.addthis.com *.cloudflare.com *.fontawesome.com *.onesignal.com *.googleapis.com",
  "blob: *.fbcdn.net *.gstatic.com *.google.com *.facebook.com *.disquscdn.com *.twitter.com https://disqus.com *.addthis.com *.facebook.net *.disqus.com *.kiss-anime.tv",
  "*.facebook.com *.searchiq.co *.cloudflare.com *.gstatic.com *.facebook.net *.google-analytics.com *.googletagmanager.com *.google.com *.googleapis.com *.twitter.com",
  ".instagram *.newrelic.com *.optimizely.com *.quantcount.com *.quantserve.com *.scorecardresearch.com *.spot.im *.twitter.com *.youtube.com *.ytimg.com",
  "blob: *.google.com *.facebook.com *.google-analytics.com *.googleapis.com *.gstatic.com *.facebook.net *.disquscdn.com https://disqus.com *.disqus.com",
  "ocookie.com *.youtube-nocookie.com zdbb.net *.zdbb.net ziffdavisinternet.com *.ziffdavisinternet.com ziffstatic.com *.ziffstatic.com",
  "child-src 'none';frame-src *;worker-src 'none';",
  ".com *.google-analytics.com",
  " *.google-analytics.com *.cloudflare.com *.gstatic.com *.google.com *.solvemedia.com",
  " *.googletagmanager.com *.cloudflare.com *.gstatic.com *.google.com *.solvemedia.com *.googlesyndication.com",
  "*.cloudflare.com *.google.com *.addthis.com *.addthisedge.com *.facebook.net *.twitter.com *.jquery.com",
  "script-src 'self' * blob: data:",
  "script-src 'self' 'unsafe-eval' 'unsafe-inline' data:",
  ".tv *.quantserve.com *.optimizely.com *.cheezburger.com *.quantcount.com *.newrelic.com *.spot.im",
  "worker-src 'none'",
  "*.zencdn.net *.fontawesome.com *.cloudflare.com *.googletagmanager.com *.bootstrapcdn.com",
  "rc 'self' *.solvemedia.com *.gstatic.com *.google.com",
  "script-src 'unsafe-inline' 'self' *.ytimg.com *.youtube.com",
  "script-src http: https: 'self' * 'unsafe-inline'",
  "*.jwpcdn.com *.gstatic.com *.googletagmanager.com *.addthis.com *.google.com",
  " *.googleapis.com *.cloudflare.com *.fluidplayer.com *.google.com *.gstatic",
  " 'unsafe-eval' *.googletagmanager.com *.jsdelivr.net http://mygoodstream.pw",
  " *.gstatic.com *.google.com *.googleapis.com",
  "*.google.com *.gstatic",
  "child-src 'self' *.camvideos.org *.cwtvembeds.com; script-src 'self' *",
  "script-src 'self' * disquscdn.com 'unsafe-inline'",
  "*.googletagmanager.com",
  "connect-src 'self' *.twitter.com *.disqus.com https://disqus.com",
  " *.googleapis.com *.gstatic.com *.google.com *.solvemedia.com",
  " 'unsafe-eval' *.hearstapps.com *.hearst.io *.hdmtools.com",
  "*.gstatic.com *.rawgit.com *.googleapis.com *.google.com",
  "disqus.com *.disqus.com disquscdn.com *.disquscdn.com",
  "*.googleapis.com *.scorecardresearch.com *.disqus",
  "script-src 'self'",
  "script-src 'unsafe-inline' 'unsafe-eval' data: *",
  "*.googleapis.com *.cloudflare.com *.bootstrapcdn",
  "*.jwplatform.com *.jwpcdn.com *.googletagmanager",
  "child-src 'self' *.onesignal.com *.facebook.com",
  " 'unsafe-eval' blob: *.gstatic.com *.cloudflare",
  " 'unsafe-eval' *.sharethis.com *.facebook.com",
  " 'unsafe-eval' *.facebook.com *.facebook.net",
  " *.facebook.net *.facebook.com *.twitter.com",
  " 'unsafe-eval' *.jwpsrv.com *.jwplayer.com",
  " *.google.com *.msembed.net *.mystream.to",
  "child-src 'none'; frame-src ",
  " 'unsafe-eval'",
  " data: *.bootstrapcdn.com *.googleapis",
  " data: *.facebook.net *.facebook.com",
  "child-src 'none';frame-src 'self' *;",
  "default-src 'self' 'unsafe-inline'",
  " http: https: blob:",
  "*.bootstrapcdn.com *.cloudflare",
  "blob: *.peer5.com *.jwpcdn.com ",
  "child-src 'self'",
  " *.google.com *.cloudflare.com",
  " *.disquscdn.com *.disqus.com",
  " data: *.fbcdn.net *.facebook",
  " *.googleapis.com",
  " hcaptcha.com *.hcaptcha.com",
  " *.pinterest.com *.onesignal",
  "https://disqus.com *.disqus",
  "*.gstatic.com *.google.com ",
  " *.4cdn.org *.4channel.org",
  " *.addthis.com *.query.com",
  "*.facebook.com *.pinterest",
  "*.facebook.net *.facebook",
  " *.scorecardresearch.com",
  " * blob: 'unsafe-inline'",
  "connect-src https: http:",
  "*.google.com",
  "*.addthis.com *.disqus",
  " *.googletagservices",
  "*.cloudflare",
  " *.bootstrapcdn.com",
  ".com *.jsdelivr.net",
  " data:",
  "style-src 'self' *",
  "connect-src 'self'",
  " *.solvemedia.com ",
  " *.tickcounter.com",
  " *.updatetube.com",
  " *.wstream.video",
  " *.disquscdn.com",
  "*.facebook.com ",
  "*.gstatic",
  " *.statcounter",
  " *.addthis.com",
  " *.histats.com",
  " http: https:",
  ".com *.jquery",
  " *.yimg.com",
  " *.alotporn",
  "*.yandex.ru",
  " *.amung.us",
  ".com",
  "'self' *; ",
  "child-src ",
  " blob:",
  " *.google",
  " *",
  " ; ",
  "*; ",
  "o",
  ".",
  "c",
  " ",
  "e",
  "s",
  "t",
  "a",
  "i",
  "'",
  "*",
  "l",
  "r",
  "n",
  "m",
  "g",
  "p",
  "f",
  "-",
  "d",
  "u",
  "b",
  "w",
  "k",
  "y",
  ":",
  "v",
  "h",
  ";",
  "q",
  "z",
  "/",
  "j",
  "x",
  "4",
  "2",
  "5"
];