export default function rc() {
  return {
    name: 'Adblocker Bot',
    email: 'adblocker-bot@users.noreply.github.com',
    plugins: ['protected-branch', 'npm'],
    labels: [
      {
        name: 'PR: Breaking Change :boom:',
        description: 'Increment major version when merged',
        changelogTitle: ':boom: Breaking Change',
        releaseType: 'major',
        overwrite: true,
        color: '#e2372b',
      },
      {
        name: 'PR: New Feature :rocket:',
        description: 'Increment minor version when merged',
        changelogTitle: ':rocket: New Feature',
        releaseType: 'minor',
        overwrite: true,
        color: '#2e449b',
      },
      {
        name: 'PR: Performance :running_woman:',
        description: 'Increment minor version when merged',
        changelogTitle: ':running_woman: Performance',
        releaseType: 'minor',
        overwrite: true,
        color: '#ead99f',
      },
      {
        name: 'PR: Bug Fix :bug:',
        description: 'Increment patch version when merged',
        changelogTitle: ':bug: Bug Fix',
        releaseType: 'patch',
        overwrite: true,
        color: '#56dd97',
      },
      {
        name: 'PR: Polish :nail_care:',
        description: 'Increment patch version when merged',
        changelogTitle: ':nail_care: Polish',
        releaseType: 'patch',
        overwrite: true,
        color: '#a9bbe8',
      },
      {
        name: 'PR: Internal :house:',
        description: 'Changes only affect internals',
        changelogTitle: ':house: Internal',
        releaseType: 'none',
        overwrite: true,
        color: '#5b1482',
      },
      {
        name: 'PR: Docs :memo:',
        description: 'Changes only affect documentation',
        changelogTitle: ':memo: Documentation',
        releaseType: 'none',
        overwrite: true,
        color: '#d2f28a',
      },
      {
        name: 'skip-release',
        description: 'Preserve the current version when merged',
        releaseType: 'skip',
        overwrite: true,
        color: '#e069cf',
      },
      {
        name: 'PR: Dependencies :nut_and_bolt:',
        description: 'Changes only update dependencies',
        changelogTitle: ':nut_and_bolt: Dependencies',
        releaseType: 'none',
        overwrite: true,
        color: '#5dbdcc',
      },
    ],
  };
}
