/*!
 * Copyright (c) 2017-present Cliqz GmbH. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

/* tslint:disable */
export default [
  "fuckadblock.js-3.2.0",
  "x2-transparent.png",
  "googlesyndication.com/adsbygoogle.js",
  "noopjs",
  "noopmp3-0.1s",
  "google-analytics.com/analytics.js",
  "1x1-transparent.gif",
  "googletagmanager.com/gtm.js",
  "noopmp4-1s",
  "ligatus.com/*/angular-tag.js",
  "amazon-adsystem.com/aax2/amzn_ads.js",
  "nooptext",
  "static.chartbeat.com/chartbeat.js",
  "widgets.outbrain.com/outbrain.js",
  "scorecardresearch.com/beacon.js",
  "google-analytics.com/cx/api.js",
  "addthis.com/addthis_widget.js",
  "32x32-transparent.png",
  "googletagservices.com/gpt.js",
  "google-analytics.com/ga.js",
  "hd-main.js",
  "noopframe",
  "silent-noeval.js",
  "popads-dummy.js",
  "fingerprint2.js",
  "popads.net.js",
  "noop.txt",
  "1x1.gif",
  "none",
  "o",
  "n",
  "p",
  "s",
  "j",
  ".",
  "a",
  "t",
  "-",
  "e",
  "m",
  "g",
  "r",
  "c",
  "1",
  "2",
  "x",
  "3",
  "l",
  "0",
  "d",
  "i",
  "k",
  "f",
  "b",
  "u",
  "/",
  "4",
  "y",
  "h",
  "*",
  "v",
  "_",
  "w",
  "z"
];
