/*!
 * Copyright (c) 2017-present Ghostery GmbH. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
/* eslint-disable prettier/prettier */
export default [
  "sandbox allow-forms allow-same-origin allow-scripts allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-top-navigation",
  "script-src 'self' 'unsafe-eval' http: https: data: blob: mediastream: filesystem:",
  "script-src 'self' data: 'unsafe-inline' 'unsafe-hashes' 'unsafe-eval'",
  "script-src 'self' 'unsafe-inline' 'unsafe-eval' ",
  " *.google.com *.gstatic.com *.googleapis.com",
  ".com *.google.com *.googletagmanager.com *.",
  "script-src 'self' '*' 'unsafe-inline'",
  "default-src 'unsafe-inline' 'self'",
  " *.google.com *.gstatic.com *.",
  "t-src 'self' 'unsafe-inline' ",
  "script-src * 'unsafe-inline'",
  ".com *.googleapis.com *.",
  " *.googletagmanager.com",
  ".com *.bootstrapcdn.com",
  "default-src 'self'",
  "frame-src 'self' *",
  " *.cloudflare.com",
  "child-src 'none';",
  "worker-src 'none'",
  "'unsafe-inline'",
  "googleapis.com",
  "unsafe-eval' ",
  "connect-src ",
  "child-src *",
  " *.gstatic",
  "google.com",
  "script-src",
  "style-src ",
  "frame-src",
  "facebook",
  "https://",
  " allow-",
  ".com *.",
  ".net *.",
  "addthis",
  "captcha",
  "gstatic",
  "youtube",
  " blob:",
  "'self'",
  "defaul",
  "disqus",
  "google",
  "jquery",
  "ation",
  "data:",
  "media",
  "scrip",
  "-src",
  ".com",
  ".net",
  "n.cc",
  " *.",
  "age",
  "avi",
  "box",
  "ent",
  "ori",
  "pic",
  "str",
  "yti",
  " '",
  " *",
  ": ",
  "*.",
  "al",
  "am",
  "an",
  "ap",
  "cd",
  "ck",
  "er",
  "es",
  "il",
  "im",
  "in",
  "lo",
  "op",
  "or",
  "re",
  "st",
  "tt",
  "wi",
  "wp",
  " ",
  "-",
  ";",
  ":",
  ".",
  "'",
  "*",
  "/",
  "1",
  "3",
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y"
];