/*!
 * Copyright (c) 2017-present Cliqz GmbH. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
/* tslint:disable quotemark */
export default [
  "sandbox allow-forms allow-same-origin allow-scripts allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-top-navigation",
  "script-src 'self' 'unsafe-eval' http: https: data: blob: mediastream: filesystem:",
  "script-src 'self' 'unsafe-inline' 'unsafe-eval' data:",
  "script-src 'self' '*' 'unsafe-inline'",
  "default-src 'unsafe-inline' 'self'",
  "script-src 'self' 'unsafe-inline' ",
  "script-src * 'unsafe-inline'",
  " *.google.com *.gstatic.com",
  ".com *.googletagmanager.com",
  ".com *.googleapis.com *.",
  " *.google-analytics.com",
  "*.gstatic.com *.google",
  " *.cloudflare.com *.",
  " *.bootstrapcdn.com",
  "frame-src 'self' *",
  " *.googleapis.com",
  "child-src 'none';",
  "worker-src 'none'",
  " *.facebook.com",
  "'unsafe-inline'",
  "'unsafe-eval' ",
  "facebook.net",
  "-src 'self'",
  "connect-src",
  "script-src ",
  "style-src *",
  ".googletag",
  "cloudflare",
  "jquery.com",
  "child-src",
  "frame-src",
  "https://",
  ".com *.",
  "'self' ",
  "addthis",
  "captcha",
  "connect",
  "default",
  "gstatic",
  " blob:",
  " data:",
  "disqus",
  "google",
  ".com",
  ".net",
  " *.",
  "age",
  "cdn",
  "dia",
  "tra",
  "yti",
  " *",
  "*.",
  "an",
  "at",
  "el",
  "er",
  "ic",
  "im",
  "in",
  "le",
  "me",
  "rc",
  "re",
  "st",
  "tt",
  "tu",
  "wi",
  "wp",
  "ww",
  " ",
  "-",
  ";",
  ":",
  ".",
  "'",
  "*",
  "/",
  "5",
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y"
];