name: Release

on:
  push:
    branches: ["master"]

jobs:
  release:
    name: Trigger release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Prepare repository
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git fetch --prune --unshallow
      - name: Enable Corepack
        run: corepack enable

      - name: Use node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          cache: yarn
          node-version-file: '.tool-versions'
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        with:
          app-id: ${{ secrets.ADBLOCKERBOT_APP_ID }}
          private-key: ${{ secrets.ADBLOCKERBOT_PRIVATE_KEY }}

      - name: Create release
        run: yarn release
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
