name: Release

on:
  push:
    branches: ["master"]

jobs:
  release:
    name: Trigger release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Prepare repository
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git fetch --prune --unshallow
      - name: Enable Corepack
        run: corepack enable

      - name: Use node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: yarn
          node-version-file: '.tool-versions'
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.ADBLOCKERBOT_APP_ID }}
          private-key: ${{ secrets.ADBLOCKERBOT_PRIVATE_KEY }}

      - name: Create release
        run: yarn release
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
